instanceName = "ec2-mack-webserver"
imageId = "ami-0ebfd941bbafe70c6"
instanceType = "t2.micro"
keyName = "key-mack-webserver"
vpcId = "vpc-0c43cc465deb50cf0"
securityGroupName = "sg-mack-webserver"
securityGroupDescription = "Grupo de seguranca para webserver"