instanceName = "ec2-mack-webserver"
imageId = "ami-0ebfd941bbafe70c6"
instanceType = "t2.micro"
keyName = "key-mack-webserver"
vpcId = "vpc-0c43cc465deb50cf0"
securityGroupName = "secg-webserver-mack"
securityGroupDescription = "Grupo de seguranca para webserver"
aws_region = "us-east-1"